// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltimateForum.Razor.Db;

#nullable disable

namespace UltimateForum.Razor.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("UltimateForum.Db.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Op")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BoardGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardGroupId");

                    b.HasIndex("Name");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.BoardGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Name");

                    b.ToTable("BoardGroups");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.BoardUserOrganizer", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DesignatedId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Since")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uuid");

                    b.HasIndex("BoardId");

                    b.HasIndex("DesignatedId");

                    b.ToTable("BoardUserOrganizers");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AttachmentUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Content");

                    b.HasIndex("CreatorId");

                    b.HasIndex("PostId");

                    b.HasIndex("TopicId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Topic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreaterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("CreaterId");

                    b.HasIndex("Title");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Board", b =>
                {
                    b.HasOne("UltimateForum.Razor.Db.Models.BoardGroup", "BoardGroup")
                        .WithMany("Boards")
                        .HasForeignKey("BoardGroupId");

                    b.Navigation("BoardGroup");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.BoardGroup", b =>
                {
                    b.HasOne("UltimateForum.Db.Models.User", "CreatedBy")
                        .WithMany("CreatedBoardGroups")
                        .HasForeignKey("CreatedById")
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.BoardUserOrganizer", b =>
                {
                    b.HasOne("UltimateForum.Razor.Db.Models.Board", "Board")
                        .WithMany("BoardUserOrganizers")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateForum.Db.Models.User", "Designated")
                        .WithMany("BoardUserOrganizers")
                        .HasForeignKey("DesignatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Designated");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Post", b =>
                {
                    b.HasOne("UltimateForum.Db.Models.User", "Creator")
                        .WithMany("CreatedPosts")
                        .HasForeignKey("CreatorId")
                        .IsRequired();

                    b.HasOne("UltimateForum.Razor.Db.Models.Post", null)
                        .WithMany("Quotting")
                        .HasForeignKey("PostId");

                    b.HasOne("UltimateForum.Razor.Db.Models.Topic", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Topic", b =>
                {
                    b.HasOne("UltimateForum.Razor.Db.Models.Board", "Board")
                        .WithMany("Topics")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateForum.Db.Models.User", "Creater")
                        .WithMany("CreatedTopics")
                        .HasForeignKey("CreaterId");

                    b.Navigation("Board");

                    b.Navigation("Creater");
                });

            modelBuilder.Entity("UltimateForum.Db.Models.User", b =>
                {
                    b.Navigation("BoardUserOrganizers");

                    b.Navigation("CreatedBoardGroups");

                    b.Navigation("CreatedPosts");

                    b.Navigation("CreatedTopics");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Board", b =>
                {
                    b.Navigation("BoardUserOrganizers");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.BoardGroup", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Post", b =>
                {
                    b.Navigation("Quotting");
                });

            modelBuilder.Entity("UltimateForum.Razor.Db.Models.Topic", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
