# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    strategy:
      matrix:
        rid: [ 'win-x64','win-arm64', 'win-x86','linux-x64', 'linux-arm64','osx-x64', 'osx-arm64' ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish ${{matrix.rid}}
      run: dotnet publish UltimateForum.Razor/UltimateForum.Razor.csproj --configuration Release -r ${{matrix.rid}} --output ./publish_output-${{matrix.rid}} -p:PublishSingleFile=true
    - name: Upload artifact for ${{matrix.rid}}
      uses: actions/upload-artifact@v4
      with:
        name: published-app-${{matrix.rid}}
        path: ./publish_output-${{matrix.rid}} # The folder containing the published files
